---
- hosts: all
  tasks:
  - name: Install python-Scapy and dependencies
    apt: name={{ item }} update_cache=yes
    loop: ['python-scapy', 'nmap', 'build-essential', 'git', 'libpcre3-dev', 'libssl-dev', 'zlib1g-dev', 'ffmpeg']
    become: yes

  - name: Install nginx and RTMP module
    command: sh /vagrant/host-setup/dashServer/nginx-rtmp.sh 
    become: yes

  - name: Copy nginx configuration file
    command: cp /vagrant/host-setup/dashServer/nginx.conf /usr/local/nginx/conf/
    become: yes

  - name: Restart nginx webserver
    command: systemctl reload nginx
    become: yes
  
  - name: Adjust arp table for client VLC
    command: ip neighbor add 192.168.50.51 lladdr 08:00:27:00:00:01 dev enp0s8 nud permanent
    become: yes
    