---
- hosts: all
  tasks:
  - name: Install python-Scapy and dependencies
    apt: name={{ item }} update_cache=yes
    loop: ['python3-scapy','python3-pip']
    become: yes

  - name: Install pythonping module
    command: pip3 install pythonping
    become: yes

  - name: Adjust arp table
    command: ip neighbor add 192.168.50.50 lladdr 08:00:27:00:00:00 dev enp0s8 nud permanent
    become: yes
  
  - name: Adjust clock timezone
    command: timedatectl set-timezone UTC
    become: yes 